### PR TITLE
Webhook for default images

### PR DESCRIPTION
**Pull request by abays**
Default container images are now handled via env vars and internal webhooks. This defaulting logic will in turn later be integrated with OpenStack Operator via webhooks there that use the new defaulting mechanism (while at the same time disabling the Octavia service operator internal webhooks in that context).

### CODE REVIEW

**Comment by abays** [comment]
> @abays: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/octavia-operator-build-deploy-kuttl 	[f1ae65e](https://github.com/openstack-k8s-operators/octavia-operator/commit/f1ae65e77c16a848f566c7dc9ce6cce5f0b17518) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_octavia-operator/109/pull-ci-openstack-k8s-operators-octavia-operator-main-octavia-operator-build-deploy-kuttl/1641380916167184384) 	false 	`/test octavia-operator-build-deploy-kuttl`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=octavia-operator&pr=109). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:abays).

The KUTTL failure in CI is not caused by changes in this PR.  I am able to reproduce it locally with the current `quay.io/openstack-k8s-operators/octavia-operator-index:latest` (the default in `install_yamls`).

Regardless, even if this KUTTL test was passing, CI will ultimately fail for this PR and all current/future PRs until we fix bundle size concerns. OpenStack operator has become too large and can no longer be installed, which thus causes CI logic to fail. We have begun to address the problem [1].

[1] https://github.com/openstack-k8s-operators/openstack-operator/pull/260

**Comment by karelyatin** [comment]
> > @abays: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> > Test name 	Commit 	Details 	Required 	Rerun command
> > ci/prow/octavia-operator-build-deploy-kuttl 	[f1ae65e](https://github.com/openstack-k8s-operators/octavia-operator/commit/f1ae65e77c16a848f566c7dc9ce6cce5f0b17518) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_octavia-operator/109/pull-ci-openstack-k8s-operators-octavia-operator-main-octavia-operator-build-deploy-kuttl/1641380916167184384) 	false 	`/test octavia-operator-build-deploy-kuttl`
> > [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=octavia-operator&pr=109). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:abays).
> 
> The KUTTL failure in CI is not caused by changes in this PR. I am able to reproduce it locally with the current `quay.io/openstack-k8s-operators/octavia-operator-index:latest` (the default in `install_yamls`).
> 
> Regardless, even if this KUTTL test was passing, CI will ultimately fail for this PR and all current/future PRs until we fix bundle size concerns. OpenStack operator has become too large and can no longer be installed, which thus causes CI logic to fail. We have begun to address the problem [1].
> 
> [1] [openstack-k8s-operators/openstack-operator#260](https://github.com/openstack-k8s-operators/openstack-operator/pull/260)

https://github.com/openstack-k8s-operators/octavia-operator/pull/104 will fix the issue with kuttl tests in octavia

**Comment by weinimo** [comment]
/retest
#104 has been merged

**Comment by weinimo** [comment]
@abays can you rebase please?

**Review by weinimo — COMMENTED** [review]
/lgtm
I'm not familiar with operator webhooks yet, though.

**Pull request merged**
