### PR TITLE
bump to golang 1.21

### PR DESCRIPTION
**Pull request by mrkisaolamb**
* bump in go.mod (base and api)
* bump go-toolset in Dockerfile
* bump in github jobs ('.github/workflows')
* Bump the golangci-lint version in the .pre-commit-config.yaml to v1.59.1 (1.60 >= golang 1.22; 1.61 >= golang 1.23)
* Bump build_root_image in .ci-operator.yaml to ci-build-root-golang-1.21-sdk-1.31

Jira: [OSPRH-6501](https://issues.redhat.com//browse/OSPRH-6501)

### CODE REVIEW

**Review by stuggi — APPROVED** [review]
/lgtm

**Review by dprince — APPROVED** [review]

**Pull request merged**
