### PR TITLE
Enable ginkgolinter

### PR DESCRIPTION
**Pull request by bshewale**

### CODE REVIEW

**Comment by bshewale** [comment]
this pr is depends-on : https://github.com/openshift/release/pull/38529

**Comment by bshewale** [comment]
/pj-rehearse pull-ci-openstack-k8s-operators-octavia-operator-main-golangci

**Comment by bshewale** [comment]
"/retest

**Review by beagles — APPROVED** [review]

**Comment by abays** [comment]
> @bshewale: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/golangci 	[778744d](https://github.com/openstack-k8s-operators/octavia-operator/commit/778744d06c4cabfb2178a0b587314aef07e45207) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_octavia-operator/128/pull-ci-openstack-k8s-operators-octavia-operator-main-golangci/1648912237991038976) 	true 	`/test golangci`
> ci/prow/octavia-operator-build-deploy-kuttl 	[4c02610](https://github.com/openstack-k8s-operators/octavia-operator/commit/4c02610df5b1aacd7fdb643795853d0c8162818d) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_octavia-operator/128/pull-ci-openstack-k8s-operators-octavia-operator-main-octavia-operator-build-deploy-kuttl/1653756224056856576) 	false 	`/test octavia-operator-build-deploy-kuttl`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=octavia-operator&pr=128). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:bshewale).

First CI error is this:

```
level=error msg="Running error: unknown linters: 'ginkgolinter', run 'golangci-lint help linters' to see the list of supported linters"
```

**Comment by son-vyas** [comment]
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_octavia-operator/128/pull-ci-openstack-k8s-operators-octavia-operator-main-octavia-operator-build-deploy-kuttl/1655541100980473856/artifacts/octavia-operator-build-deploy-kuttl/openstack-k8s-operators-gather/build-log.txt

**Review by weinimo — APPROVED** [review]

**Pull request merged**
