### PR TITLE
[18.0-fr1] Ensure nodeSelector logic is consistent for all operators

### PR DESCRIPTION
**Pull request by olliewalsh**
Manual cherry-pick of https://github.com/openstack-k8s-operators/octavia-operator/pull/417 due to merge conflicts

### CODE REVIEW

**Review by abays — APPROVED** [review]
/lgtm

**Comment by olliewalsh** [comment]
/override ci/prow/octavia-operator-build-deploy  ci/prow/octavia-operator-build-deploy-kuttl
will create follow-up DNM PRs to test as there is a circular dependency with the openstack-operator patch

**Pull request merged**
