### PR TITLE
Update httpd images

### PR DESCRIPTION
**Pull request by gthiemonge**

### CODE REVIEW

**Comment by abays** [comment]
```
Unable to connect to the server: http2: client connection lost
```

/test octavia-operator-build-deploy-kuttl

**Review by abays — APPROVED** [review]
/lgtm

**Comment by abays** [comment]
@gthiemonge This is hitting the "stuck Keystone delete" problem we were seeing elsewhere yesterday:

```
oc kustomize /alabama/install_yamls/out/octavia-kuttl-tests/keystone/cr | oc delete --ignore-not-found=true -f -
keystoneapi.keystone.openstack.org "keystone" deleted
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:169","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 2h0m0s timeout","severity":"error","time":"2024-04-04T09:53:56Z"}
```

**Comment by abays** [comment]
Trying again

/test octavia-operator-build-deploy-kuttl

**Comment by abays** [comment]
> @gthiemonge This is hitting the "stuck Keystone delete" problem we were seeing elsewhere yesterday:
> 
> ```
> oc kustomize /alabama/install_yamls/out/octavia-kuttl-tests/keystone/cr | oc delete --ignore-not-found=true -f -
> keystoneapi.keystone.openstack.org "keystone" deleted
> {"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:169","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 2h0m0s timeout","severity":"error","time":"2024-04-04T09:53:56Z"}
> ```

Still happening, but I have not been able to reproduce this locally:

```
oc kustomize /alabama/install_yamls/out/octavia-kuttl-tests/keystone/cr | oc delete --ignore-not-found=true -f -
keystoneapi.keystone.openstack.org "keystone" deleted
{"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:169","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 2h0m0s timeout","severity":"error","time":"2024-04-05T13:59:28Z"}
```

**Comment by gthiemonge** [comment]
> > @gthiemonge This is hitting the "stuck Keystone delete" problem we were seeing elsewhere yesterday:
> > ```
> > oc kustomize /alabama/install_yamls/out/octavia-kuttl-tests/keystone/cr | oc delete --ignore-not-found=true -f -
> > keystoneapi.keystone.openstack.org "keystone" deleted
> > {"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:169","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 2h0m0s timeout","severity":"error","time":"2024-04-04T09:53:56Z"}
> > ```
> 
> Still happening, but I have not been able to reproduce this locally:
> 
> ```
> oc kustomize /alabama/install_yamls/out/octavia-kuttl-tests/keystone/cr | oc delete --ignore-not-found=true -f -
> keystoneapi.keystone.openstack.org "keystone" deleted
> {"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:169","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 2h0m0s timeout","severity":"error","time":"2024-04-05T13:59:28Z"}
> ```

@abays do you think it could be due to something that is in the octavia operator? or is it a really random issue?

**Comment by abays** [comment]
> > > @gthiemonge This is hitting the "stuck Keystone delete" problem we were seeing elsewhere yesterday:
> > > ```
> > > oc kustomize /alabama/install_yamls/out/octavia-kuttl-tests/keystone/cr | oc delete --ignore-not-found=true -f -
> > > keystoneapi.keystone.openstack.org "keystone" deleted
> > > {"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:169","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 2h0m0s timeout","severity":"error","time":"2024-04-04T09:53:56Z"}
> > > ```
> > 
> > 
> > Still happening, but I have not been able to reproduce this locally:
> > ```
> > oc kustomize /alabama/install_yamls/out/octavia-kuttl-tests/keystone/cr | oc delete --ignore-not-found=true -f -
> > keystoneapi.keystone.openstack.org "keystone" deleted
> > {"component":"entrypoint","file":"k8s.io/test-infra/prow/entrypoint/run.go:169","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 2h0m0s timeout","severity":"error","time":"2024-04-05T13:59:28Z"}
> > ```
> 
> @abays do you think it could be due to something that is in the octavia operator? or is it a really random issue?

@gthiemonge I think it's a problem with Keystone, actually.  I think it is exacerbated by the fact that the Octavia KUTTL tests use so many other operators as dependencies.  The `KeystoneService` reconcile logic seems, to me, to be the problem.  Somehow having multiple operators and deleting their resources independently (i.e. via `oc delete <resource>`) seems to have a chance to mess with how their associated `KeystoneService` resources add and remove finalizers from the `KeystoneAPI` resource.

**Pull request merged**
